services:
 web:
   build:
     context: ./djackets_django
   volumes:
     - ./djackets_django:/app
     - ./media:/app/media
   ports:
     - "8000:8000"
   depends_on:
     - db

 db:
   image: postgres:13
   environment:
     POSTGRES_DB: your_db_name
     POSTGRES_USER: your_user
     POSTGRES_PASSWORD: your_password
   volumes:
     - postgres_data:/var/lib/postgresql/data

 vue:
   build:
     context: ./djackets_vue
   ports:
     - "8080:8080"

volumes:
 postgres_data:
